name: firebase_app_check_platform_interface
description: A common platform interface for the firebase_app_check plugin.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_app_check/firebase_app_check_platform_interface
version: 0.0.1+6

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  firebase_core: ^1.7.0
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  firebase_core_platform_interface: ^4.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
