name: firebase_app_check
description: App Check works alongside other Firebase services to help protect your backend resources from abuse, such as billing fraud or phishing.
homepage: https://firebase.flutter.dev/docs/app-check/overview
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_app_check/firebase_app_check
version: 0.0.2+2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  firebase_app_check_platform_interface: ^0.0.1+6
  firebase_app_check_web: ^0.0.1+6
  firebase_core: ^1.7.0
  firebase_core_platform_interface: ^4.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.appcheck
        pluginClass: FlutterFirebaseAppCheckPlugin
      ios:
        pluginClass: FLTFirebaseAppCheckPlugin
      macos:
        pluginClass: FLTFirebaseAppCheckPlugin
      web:
        default_package: firebase_app_check_web
